version: '3.7'
services:
  dev:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/src/
      - venv_bin:/app/backend/.venv
      - vscode_extension:/home/user/.vscode-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.gitconfig:/.gitconfig
      - ~/.ssh/:/home/user/.ssh/
    tty: true
  localstack:
    image: localstack/localstack:1.2.0
    environment:
      DEBUG: false
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: /tmp/localstack
      SERVICES: s3,sqs
      HOSTNAME_EXTERNAL: localstack.invoice.klavis.link
      AWS_DEFAULT_REGION: ap-northeast-1
      DISABLE_CORS_CHECKS: 1
      DISABLE_CUSTOM_CORS_S3: 1
    volumes:
      - localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tools/localstack.sh:/docker-entrypoint-initaws.d/localstack.sh
    healthcheck:
      test:
        - CMD
        - 'curl'
        - 'http://localhost:4566/health'
        - 'grep'
        - '"initScripts": "initialized"'
      interval: 2s
      start_period: 20s
      retries: 10
      timeout: 10s
volumes:
  venv_bin:
  localstack:
  vscode_extension:
networks:
  default:
